{{ define "deployment" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment-{{ .Replicas }}
spec:
  selector:
    matchLabels:
      app: my-app
  replicas: {{ .Replicas }}
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-container
        image: my-image:1.0.0
        ports:
        - containerPort: 80
{{ end }}
