apiVersion: batch/v1
kind: Job
metadata:
  name: my-job
spec:
  template:
    metadata:
      name: my-job
    spec:
      containers:
      - name: my-container
        image: my-image
        command: ["sh", "-c", "echo Hello, World! && sleep 3600"]
      restartPolicy: Never
  backoffLimit: 4
